
PACKAGE = org.web3d.x3d.sai.pickingsensor

SOURCE = \
  LinePicker.java \
  PickableGroup.java \
  PointPicker.java \
  PrimitivePicker.java \
  VolumePicker.java \

include ${PROJECT_ROOT}/make/Makefile.jav
