
PACKAGE = org.xj3d.sai.internal.node.geometry2d

SOURCE = \
  SAIPolyline2D.java \
  SAIPolypoint2D.java \
  SAIRectangle2D.java \
  SAITriangleSet2D.java \

include ${PROJECT_ROOT}/make/Makefile.jav
