#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.web3d.vrml.scripting.jsai directory
#
# Author: Justin Couch
# Version: $Revision: 1.14 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.scripting.sai

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = SAIComponentInfo.java \
    SAIProfileInfo.java \
    FieldListenerMulticaster.java \
    SAIFieldEvent.java \
    SAIFieldDefinition.java \
    FieldAccessListener.java \
    BaseField.java \
    BaseNodeFactory.java \
    FieldFactory.java \
    NodeField.java \
    BaseNode.java \
    DefaultBaseNodeFactory.java \
    SAISFBool.java \
    SAISFColor.java \
    SAISFColorRGBA.java \
    SAISFDouble.java \
    SAISFFloat.java \
    SAISFImage.java \
    SAISFInt32.java \
    SAISFNode.java \
    SAISFRotation.java \
    SAISFString.java \
    SAISFTime.java \
    SAISFVec2f.java \
    SAISFVec2d.java \
    SAISFVec3f.java \
    SAISFVec3d.java \
    BaseMField.java \
    SAIMFBool.java \
    SAIMFColor.java \
    SAIMFColorRGBA.java \
    SAIMFDouble.java \
    SAIMFFloat.java \
    SAIMFImage.java \
    SAIMFInt32.java \
    SAIMFNode.java \
    SAIMFRotation.java \
    SAIMFString.java \
    SAIMFTime.java \
    SAIMFVec2f.java \
    SAIMFVec2d.java \
    SAIMFVec3f.java \
    SAIMFVec3d.java \
    SAIVRMLScene.java \
    DefaultFieldFactory.java \
    SAIScriptNodeImpl.java \
    SAIProtoInstanceImpl.java \
    SAIProtoDeclaration.java \
    SAIExternProtoDeclaration.java \
    SAIRoute.java \
    BaseExecutionContext.java \
    WorldScene.java \
    InternalBrowser.java \
    JavaSAIScriptWrapper.java \
    JavaSAIScriptBrowserFactory.java \
    JavaSAIScriptEngine.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

# If the package requires extra classes outside the JDK, the JAR files that 
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = j3d-org-all_0.9.0.jar


include ${PROJECT_ROOT}/make/Makefile.jav
