#*********************************************************************
#
#  (C) 2006 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.xj3d.ui.swt.net.content directory
#
# Author: Rex Melton
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = org.xj3d.ui.swt.net.content

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  SWTImageContentHandler.java \
  SWTContentHandlerFactory.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

JARS_3RDPARTY= uri.jar org.eclipse.swt.win32.win32.x86_3.2.0.jar

include ${PROJECT_ROOT}/make/Makefile.jav
