#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.xj3d.sai directory
#
# Author: Justin Couch
# Version: $Revision: 1.9 $
#
#*********************************************************************

PACKAGE = org.xj3d.sai

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = Xj3DViewpoint.java \
  Xj3DNavigationUIListener.java \
  Xj3DNavigationUIManager.java \
  Xj3DCursorFilter.java \
  Xj3DCursorUIManager.java \
  Xj3DStatusListener.java \
  Xj3DCADViewListener.java \
  Xj3DCADView.java \
  Xj3DErrorReporter.java \
  Xj3DBrowser.java \
  BrowserInterfaceTypes.java \
  BrowserConfig.java \
  UndefinedX3DNodeTypes.java \
  X3DNodeTypeMapper.java \
  UndefinedX3DFieldTypes.java \
  X3DFieldTypeMapper.java \
  X3DNodeComponentMapper.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

JARS_3RDPARTY=

include ${PROJECT_ROOT}/make/Makefile.jav
