
PACKAGE = org.xj3d.sai.internal.node.cadgeometry

SOURCE = \
  SAICADAssembly.java \
  SAICADFace.java \
  SAICADLayer.java \
  SAICADPart.java \
  SAIQuadSet.java \

include ${PROJECT_ROOT}/make/Makefile.jav
