
PACKAGE = org.xj3d.sai.internal.node.core

SOURCE = \
  SAIMetadataDouble.java \
  SAIMetadataFloat.java \
  SAIMetadataInteger.java \
  SAIMetadataSet.java \
  SAIMetadataString.java \

include ${PROJECT_ROOT}/make/Makefile.jav
