#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.web3d.vrml.renderer.norender.nodes.render
# directory
#
# Author: Justin Couch
# Version: $Revision: 1.5 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.renderer.norender.nodes.render

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = NRNormal.java \
  NRColor.java \
  NRColorRGBA.java \
  NRCoordinate.java \
  NRPointSet.java \
  NRLineSet.java \
  NRIndexedLineSet.java \
  NRTriangleSet.java \
  NRTriangleFanSet.java \
  NRTriangleStripSet.java \
  NRIndexedTriangleSet.java \
  NRIndexedTriangleFanSet.java \
  NRIndexedTriangleStripSet.java 

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

# If the package requires extra classes outside the JDK, the JAR files that 
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY =

include ${PROJECT_ROOT}/make/Makefile.jav
