#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Author: Justin Couch
# Version: $Revision: 1.2 $
#
#*********************************************************************

# Names of grammar types to be compiled. These can be declared in any
# order although we always go first to last
GRAMMARS = vrml \
  x3d

include $(PROJECT_ROOT)/make/Makefile.javacc
