
PACKAGE = org.web3d.x3d.sai.particlesystems

SOURCE = \
  ExplosionEmitter.java \
  GravityPhysicsModel.java \
  ParticleSystem.java \
  PointEmitter.java \
  PolylineEmitter.java \
  WindPhysicsModel.java \

include ${PROJECT_ROOT}/make/Makefile.jav
