#*********************************************************************
#
#  (C) 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = 2.0/spec

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = vrml.properties \

include $(PROJECT_ROOT)/make/Makefile.config
