#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.web3d.x3d.jaxp directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = org.web3d.x3d.jaxp

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = X3DErrorHandler.java \
    X3DEntityResolver.java
#    X3DConstants.java \
#	X3DDocumentBuilder.java \
#	X3DDocumentBuilderFactory.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 


include ${PROJECT_ROOT}/make/Makefile.jav
