
PACKAGE = org.web3d.x3d.sai.interpolation

SOURCE = \
  ColorInterpolator.java \
  CoordinateInterpolator.java \
  CoordinateInterpolator2D.java \
  NormalInterpolator.java \
  OrientationInterpolator.java \
  PositionInterpolator.java \
  PositionInterpolator2D.java \
  ScalarInterpolator.java \

include ${PROJECT_ROOT}/make/Makefile.jav
