
PACKAGE = org.web3d.x3d.sai.rendering

SOURCE = \
  Color.java \
  ColorRGBA.java \
  Coordinate.java \
  IndexedLineSet.java \
  IndexedTriangleFanSet.java \
  IndexedTriangleSet.java \
  IndexedTriangleStripSet.java \
  LineSet.java \
  Normal.java \
  PointSet.java \
  TriangleFanSet.java \
  TriangleSet.java \
  TriangleStripSet.java \

include ${PROJECT_ROOT}/make/Makefile.jav
