#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.web3d.x3d.dom.swing directory
#
# Author: Justin Couch
# Version: $Revision: 1.2 $
#
#*********************************************************************

PACKAGE = org.web3d.x3d.dom.swing

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = DOMTreeNode.java \
    DOMTreeModel.java \
    DOMTreeCellEditor.java \
	DOMTreeCellRenderer.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 


include ${PROJECT_ROOT}/make/Makefile.jav
