#*********************************************************************
#
#  (C) 2008 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the xj3d.filter.node directory
#
# Author: Rex Melton
# Version: $Revision: 1.3 $
#
#*********************************************************************

PACKAGE = xj3d.filter.node

# 
SOURCE = \
  Encodable.java \
  AbstractEncodable.java \
  EncodableFactory.java \
  Color.java \
  Coordinate.java \
  Normal.java \
  TextureCoordinate.java \
  Geometry.java \
  ComposedGeometry.java \
  IndexedTriangleFanSet.java \
  IndexedTriangleSet.java \
  IndexedTriangleStripSet.java \
  TriangleFanSet.java \
  TriangleSet.java \
  TriangleStripSet.java \
  GeometryConverter.java \
  Material.java \
  Appearance.java \
  Shape.java \
  AbstractGroup.java \
  Group.java \
  TransformMatrix.java \
  Transform.java \
  Viewpoint.java \
  Scene.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY=vecmath.jar

include ${PROJECT_ROOT}/make/Makefile.jav
