
PACKAGE = org.xj3d.sai.internal.node.shape

SOURCE = \
  SAIAppearance.java \
  SAILineProperties.java \
  SAIMaterial.java \
  SAIShape.java \
  SAITwoSidedMaterial.java \

include ${PROJECT_ROOT}/make/Makefile.jav
