
PACKAGE = org.xj3d.sai.internal.node.pointingdevicesensor

SOURCE = \
  SAICylinderSensor.java \
  SAIPlaneSensor.java \
  SAISphereSensor.java \
  SAITouchSensor.java \

include ${PROJECT_ROOT}/make/Makefile.jav
