#*********************************************************************
#
#  (C) 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Justin Couch
# Version: $Revision: 1.3 $
#
#*********************************************************************

# Names of packages to be compiled. These are declared in the order that
# they are to be compiled in. We create one at a time
BUILD_ORDER = common \
  2.0 \
  2.0/spec \
  3.0 \
  3.0/spec \
  3.0/component \
  3.0/profile \
  3.1 \
  3.1/spec \
  3.1/component \
  3.1/profile \
  3.2 \
  3.2/spec \
  3.2/component \
  3.2/profile \

# 3rd party libraries that need including.
JARS_3RDPARTY=

# Names of JAR files we want to create
JARS = xj3d-config.jar

# Definitions of setup information if we are making a self-executable JAR
MAIN_CLASS     =
MAIN_PACKAGE   =
MAIN_JAR       = xj3d-config.jar

include $(PROJECT_ROOT)/make/Makefile.config
