
PACKAGE = org.web3d.x3d.sai.geometry3d

SOURCE = \
  Box.java \
  Cone.java \
  Cylinder.java \
  ElevationGrid.java \
  Extrusion.java \
  IndexedFaceSet.java \
  Sphere.java \

include ${PROJECT_ROOT}/make/Makefile.jav
