
PACKAGE = org.xj3d.sai.internal.node.interpolation

SOURCE = \
  SAIColorInterpolator.java \
  SAICoordinateInterpolator.java \
  SAICoordinateInterpolator2D.java \
  SAINormalInterpolator.java \
  SAIOrientationInterpolator.java \
  SAIPositionInterpolator.java \
  SAIPositionInterpolator2D.java \
  SAIScalarInterpolator.java \

include ${PROJECT_ROOT}/make/Makefile.jav
