#*********************************************************************
#
#  (C) 2001 - 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.xj3d.io directory
#
# Author: Alan Hudson
# Version: $Revision: 1.2 $
#
#*********************************************************************

PACKAGE = org.xj3d.io

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  ReadProgressListener.java \
  ReportableInputStream.java \
  ReportableInputStreamReader.java \
  ReportableReader.java \
  SequenceReader.java \
  BlockDataInputStream.java \
  StreamContentContainer.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =


include ${PROJECT_ROOT}/make/Makefile.jav
