#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Justin Couch
# Version: $Revision: 1.3 $
#
#*********************************************************************

# This is a standard makefile. All the normal make rules apply


# Names of all applications to be compiled, which is the default system.
all: installer browser converter

browser:
	cd browser && make all

converter:
	cd converter && make all

installer:
	cd installer && make all

include $(PROJECT_ROOT)/make/Makefile.jav
