
PACKAGE = org.web3d.x3d.sai.texturing

SOURCE = \
  ImageTexture.java \
  MovieTexture.java \
  MultiTexture.java \
  MultiTextureCoordinate.java \
  MultiTextureTransform.java \
  PixelTexture.java \
  TextureCoordinate.java \
  TextureCoordinateGenerator.java \
  TextureProperties.java \
  TextureTransform.java \

include ${PROJECT_ROOT}/make/Makefile.jav
