
PACKAGE = org.web3d.x3d.sai.navigation

SOURCE = \
  Billboard.java \
  Collision.java \
  LOD.java \
  NavigationInfo.java \
  OrthoViewpoint.java \
  Viewpoint.java \

include ${PROJECT_ROOT}/make/Makefile.jav
