
PACKAGE = org.web3d.x3d.sai.eventutilities

SOURCE = \
  BooleanFilter.java \
  BooleanSequencer.java \
  BooleanToggle.java \
  BooleanTrigger.java \
  IntegerSequencer.java \
  IntegerTrigger.java \
  TimeTrigger.java \

include ${PROJECT_ROOT}/make/Makefile.jav
