#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.web3d.vrml.renderer.j3d.nodes directory
#
# Author: Justin Couch
# Version: $Revision: 1.27 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.renderer.j3d.nodes

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = J3DVRMLNode.java \
    J3DParentPathRequestHandler.java \
    J3DPathAwareNodeType.java \
    J3DGlobalStatus.java \
    J3DPickableTargetNodeType.java \
    J3DPickingSensorNodeType.java \
    J3DNode.java \
    J3DTextureConstConverter.java \
    J3DAreaListener.java \
    J3DVisibilityListener.java \
    J3DUserData.java \
    J3DGroupingNode.java \
    J3DWorldRootNodeType.java \
    J3DViewpointNodeType.java \
    J3DBackgroundNodeType.java \
    J3DFogNodeType.java \
    J3DGeometryListener.java \
    J3DAppearanceListener.java \
    J3DGeometryNodeType.java \
    J3DTextNodeType.java \
    J3DGeometryNode.java \
    J3DComponentGeometryNode.java \
    J3DTransparencyListener.java \
    J3DMaterialNodeType.java \
    J3DTextureTransformListener.java \
    J3DTextureCoordinateTransformNodeType.java \
    J3DAppearanceNodeType.java \
    J3DLightNodeType.java \
    J3DLightNode.java \
    J3DIndexedGeometry.java \
    J3DTextureTransformListener.java \
    J3DOverlayItemNodeType.java \
    J3DOverlayStructureNodeType.java \
    J3DTerrainSource.java \
    J3DLinePropertiesNodeType.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = j3d-org-all_0.9.0.jar

include ${PROJECT_ROOT}/make/Makefile.jav
