#*********************************************************************
#
#  (C) 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Alan Hudson
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = branding

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = yumetech-16x16.gif

include $(PROJECT_ROOT)/make/Makefile.images
