/*****************************************************************************
 *                        Web3d.org Copyright (c) 2001 - 2005
 *                               Java Source
 *
 * This source is licensed under the GNU LGPL v2.1
 * Please read http://www.gnu.org/copyleft/lgpl.html for more information
 *
 * This software comes with the standard NO WARRANTY disclaimer for any
 * purpose. Use it at your own risk. If there's a problem you get to fix it.
 *
 ****************************************************************************/

package org.web3d.vrml.renderer.ogl.browser;

// External imports
// None

// Local imports
import org.web3d.util.DefaultErrorReporter;
import org.web3d.util.ErrorReporter;

import org.xj3d.core.eventmodel.LayerManager;
import org.xj3d.core.eventmodel.LayerManagerFactory;

/**
 * Layer manager factory instance that creates OpenGL-specific layers
 * handlers.
 *
 * @author Justin Couch
 * @version $Revision: 1.3 $
 */
public class OGLLayerManagerFactory implements LayerManagerFactory {

    /** The error errorReporter instance */
    private ErrorReporter errorReporter;

    /**
     * Create a new default instance of this factory.
     */
    public OGLLayerManagerFactory() {
        errorReporter = DefaultErrorReporter.getDefaultReporter();
    }

    //----------------------------------------------------------
    // Methods defined by LayerManagerFactory
    //----------------------------------------------------------

    /**
     * Create a new layer manager instance.
     *
     * @return a new clean layer manager
     */
    public LayerManager createLayerManager() {
        LayerManager lm = new OGLLayerManager();
        lm.setErrorReporter(errorReporter);

        return lm;
    }

    /**
     * Register an error errorReporter with the factory instance so that any errors
     * generated by the creation of nodes can be reported in a nice, pretty
     * fashion. Setting a value of null will clear the currently set errorReporter.
     * If one is already set, the new value replaces the old.
     *
     * @param reporter The instance to use or null
     */
    public void setErrorReporter(ErrorReporter reporter) {
        errorReporter = reporter;

        if(errorReporter == null)
            errorReporter = DefaultErrorReporter.getDefaultReporter();
    }
}
