#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.web3d.vrml.renderer.common.geospatial directory
#
# Author: Alan Hudson
# Version: $Revision: 1.5 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.renderer.common.geospatial

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = GTTransformUtils.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib

JARS_3RDPARTY = gt2-main-2.3.1.jar gt2-referencing-2.3.1.jar geoapi-nogenerics-2.1-M2.jar jsr108-0.01.jar vecmath.jar

include ${PROJECT_ROOT}/make/Makefile.jav
