
PACKAGE = org.xj3d.sai.internal.node.pickingsensor

SOURCE = \
  SAILinePicker.java \
  SAIPickableGroup.java \
  SAIPointPicker.java \
  SAIPrimitivePicker.java \
  SAIVolumePicker.java \

include ${PROJECT_ROOT}/make/Makefile.jav
