#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.web3d.vrml.scripting.jsai directory
#
# Author: Justin Couch
# Version: $Revision: 1.6 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.scripting.jsai

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  FieldFactory.java \
  NodeField.java \
  JSAINode.java \
  JSAISFBool.java \
  JSAISFColor.java \
  JSAISFFloat.java \
  JSAISFImage.java \
  JSAISFInt32.java \
  JSAISFNode.java \
  JSAISFRotation.java \
  JSAISFString.java \
  JSAISFTime.java \
  JSAISFVec2f.java \
  JSAISFVec3f.java \
  JSAIMFColor.java \
  JSAIMFFloat.java \
  JSAIMFInt32.java \
  JSAIMFNode.java \
  JSAIMFRotation.java \
  JSAIMFString.java \
  JSAIMFTime.java \
  JSAIMFVec2f.java \
  JSAIMFVec3f.java \
  JSAIConstSFBool.java \
  JSAIConstSFColor.java \
  JSAIConstSFFloat.java \
  JSAIConstSFImage.java \
  JSAIConstSFInt32.java \
  JSAIConstSFNode.java \
  JSAIConstSFRotation.java \
  JSAIConstSFString.java \
  JSAIConstSFTime.java \
  JSAIConstSFVec2f.java \
  JSAIConstSFVec3f.java \
  JSAIConstMFColor.java \
  JSAIConstMFFloat.java \
  JSAIConstMFInt32.java \
  JSAIConstMFNode.java \
  JSAIConstMFRotation.java \
  JSAIConstMFString.java \
  JSAIConstMFTime.java \
  JSAIConstMFVec2f.java \
  JSAIConstMFVec3f.java \
  JSAIFieldFactory.java \
  VRML97ScriptEvent.java \
  VRML97ScriptWrapper.java \
  ScriptBrowser.java \
  VRML97ScriptBrowserFactory.java \
  VRML97ScriptEngine.java 

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 


include ${PROJECT_ROOT}/make/Makefile.jav
