
PACKAGE = org.xj3d.sai.internal.node.navigation

SOURCE = \
  SAIBillboard.java \
  SAICollision.java \
  SAILOD.java \
  SAINavigationInfo.java \
  SAIOrthoViewpoint.java \
  SAIViewpoint.java \

include ${PROJECT_ROOT}/make/Makefile.jav
