
PACKAGE = org.xj3d.sai.internal.node.particlesystems

SOURCE = \
  SAIExplosionEmitter.java \
  SAIGravityPhysicsModel.java \
  SAIParticleSystem.java \
  SAIPointEmitter.java \
  SAIPolylineEmitter.java \
  SAIWindPhysicsModel.java \

include ${PROJECT_ROOT}/make/Makefile.jav
