/*****************************************************************************
 *                        Web3d.org Copyright (c) 2001 - 2005
 *                               Java Source
 *
 * This source is licensed under the GNU LGPL v2.1
 * Please read http://www.gnu.org/copyleft/lgpl.html for more information
 *
 * This software comes with the standard NO WARRANTY disclaimer for any
 * purpose. Use it at your own risk. If there's a problem you get to fix it.
 *
 ****************************************************************************/

package org.web3d.vrml.lang;

// External imports
// none

// Local imports
// none

/**
 * Exception indicating that a definition of a template node is not valid.
 * <P>
 *
 * An invalid template declaration may occur for one of several reasons, but
 * usually just due to poor synatx. The error may be generated by a parser or
 * by the runtime code as the user interacts with the system.
 *
 * @author Justin Couch
 * @version $Revision: 1.4 $
 */
public class InvalidTemplateException extends VRMLException {

    /**
     * Create a new exception with no message.
     *
     * @param name The name of the template that caused the error
     */
    public InvalidTemplateException(String name) {
    }

    /**
     * Create a new exception with a message.
     *
     * @param name The name of the template that caused the error
     * @param msg The message associated with this exception
     */
    public InvalidTemplateException(String name, String msg) {
        super(msg);
    }
}
