#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.web3d.vrml.lang directory
#
# Author: Justin Couch
# Version: $Revision: 1.17 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.lang

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = FieldConstants.java \
    TypeConstants.java \
    TextureConstants.java \
    VRMLException.java \
    InvalidRouteException.java \
    UnsupportedSpecVersionException.java \
    UnsupportedProfileException.java \
    UnsupportedComponentException.java \
    FieldException.java \
    FieldExistsException.java \
    InvalidFieldException.java \
    InvalidFieldFormatException.java \
    InvalidFieldValueException.java \
    InvalidFieldConnectionException.java \
    InvalidFieldTypeException.java \
    NodeException.java \
    InvalidNodeTypeException.java \
    UnsupportedNodeException.java \
    UnknownTemplateException.java \
    InvalidTemplateException.java \
    ComponentInfo.java \
    ProfileInfo.java \
    VRMLFieldDeclaration.java \
    VRMLNode.java \
    VRMLNodeTemplate.java \
    VRMLNodeFactory.java \
    InvalidFieldAccessException.java \
    SceneMetaData.java \
    BasicScene.java \
    ROUTE.java \
    VRMLExecutionSpace.java \
    NodeTemplateToInstanceCreator.java \
    AbstractScene.java \
    WriteableSceneMetaData.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =


include ${PROJECT_ROOT}/make/Makefile.jav
