#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.web3d.x3d.dom.j3d directory
#
# Author: Alan Hudson
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = org.web3d.x3d.dom.j3d

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = DOMtoJ3DException.java \
	DOMtoJ3D.java \
	TestDOMtoJ3D.java \
	DOMEventHandler.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 


include ${PROJECT_ROOT}/make/Makefile.jav
