
PACKAGE = org.xj3d.sai.internal.node.rigidbodyphysics

SOURCE = \
  SAIBallJoint.java \
  SAICollidableOffset.java \
  SAICollidableShape.java \
  SAICollisionCollection.java \
  SAICollisionSensor.java \
  SAICollisionSpace.java \
  SAIContact.java \
  SAIDoubleAxisHingeJoint.java \
  SAIMotorJoint.java \
  SAIRigidBodyCollection.java \
  SAISingleAxisHingeJoint.java \
  SAISliderJoint.java \
  SAIUniversalJoint.java \

include ${PROJECT_ROOT}/make/Makefile.jav
