#*********************************************************************
#
#  (C) 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Alan Hudson
# Version: $Revision: 1.6 $
#
#*********************************************************************

PACKAGE = navigation

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = ButtonBack.gif \
        ButtonConsole.gif \
        ButtonExamine.gif \
        ButtonFly.gif \
        ButtonForward.gif \
        ButtonHome.gif \
        ButtonFit.gif \
        ButtonPan.gif \
        ButtonTilt.gif \
        ButtonWalk.gif \
        ButtonLookat.gif \
        CursorExamine.gif \
        CursorFly.gif \
        CursorPan.gif \
        CursorTarget.gif \
        CursorTilt.gif \
        CursorWalk.gif \
        CursorLookat.gif \
        CursorNone.gif \
        drag.gif \
        link.gif \
        touch.gif \
        CursorTExamine.gif \
        CursorTPan.gif \
        ButtonTExamine.gif \
        

include $(PROJECT_ROOT)/make/Makefile.images
