#*********************************************************************
#
#  (C) 2006 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.xj3d.ui.awt.net.content directory
#
# Author: Rex Melton
# Version: $Revision: 1.2 $
#
#*********************************************************************

PACKAGE = org.xj3d.ui.awt.net.content

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  AWTImageContentHandler.java \
  AWTContentHandlerFactory.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

JARS_3RDPARTY= uri.jar j3d-org-all_0.9.0.jar 

include ${PROJECT_ROOT}/make/Makefile.jav
