
PACKAGE = org.xj3d.sai.internal.node.grouping

SOURCE = \
  SAIGroup.java \
  SAIStaticGroup.java \
  SAISwitch.java \
  SAITransform.java \
  SAIWorldInfo.java \

include ${PROJECT_ROOT}/make/Makefile.jav
