
PACKAGE = org.web3d.x3d.sai.core

SOURCE = \
  MetadataDouble.java \
  MetadataFloat.java \
  MetadataInteger.java \
  MetadataSet.java \
  MetadataString.java \

include ${PROJECT_ROOT}/make/Makefile.jav
