
PACKAGE = org.xj3d.sai.internal.node.texturing

SOURCE = \
  SAIImageTexture.java \
  SAIMultiTexture.java \
  SAIMultiTextureCoordinate.java \
  SAIMultiTextureTransform.java \
  SAIPixelTexture.java \
  SAITextureCoordinate.java \
  SAITextureCoordinateGenerator.java \
  SAITextureProperties.java \
  SAITextureTransform.java \

include ${PROJECT_ROOT}/make/Makefile.jav
