#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.web3d.x3d.sai directory
#
# Author: Justin Couch
# Version: $Revision: 1.18 $
#
#*********************************************************************

PACKAGE = org.web3d.x3d.sai

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = X3DException.java \
  URLUnavailableException.java \
  NoSuchBrowserException.java \
  NotSupportedException.java \
  InvalidX3DException.java \
  InvalidURLException.java \
  InvalidNodeException.java \
  InvalidBrowserException.java \
  InvalidExecutionContextException.java \
  InvalidFieldException.java \
  InvalidFieldValueException.java \
  InvalidReadableFieldException.java \
  InvalidWritableFieldException.java \
  InvalidDocumentException.java \
  InvalidRouteException.java \
  InvalidProtoException.java \
  InvalidOperationTimingException.java \
  ImportedNodeException.java \
  InsufficientCapabilitiesException.java \
  ConnectionException.java \
  NodeUnavailableException.java \
  NodeInUseException.java \
  BrowserNotSharedException.java \
  X3DFieldEvent.java \
  X3DFieldEventListener.java \
  BrowserEvent.java \
  BrowserListener.java \
  X3DFieldTypes.java \
  X3DLoadStateTypes.java \
  X3DFieldDefinition.java \
  X3DField.java \
  X3DNodeTypes.java \
  X3DMetadataObject.java \
  X3DNode.java \
  X3DProtoInstance.java \
  X3DProtoDeclaration.java \
  X3DExternProtoDeclaration.java \
  ComponentInfo.java \
  ProfileInfo.java \
  X3DRoute.java \
  X3DExecutionContext.java \
  X3DScene.java \
  Browser.java \
  ExternalBrowser.java \
  X3DComponent.java \
  BrowserFactoryImpl.java \
  BrowserFactory.java \
  DefaultBrowserImpl.java \
  X3DUrlObject.java \
  X3DBoundedObject.java \
  X3DFogObject.java \
  X3DPickableObject.java \
  X3DAppearanceChildNode.java \
  X3DMaterialNode.java \
  X3DTextureNode.java \
  X3DTexture2DNode.java \
  X3DTextureTransformNode.java \
  X3DAppearanceNode.java \
  X3DGeometricPropertyNode.java \
  X3DColorNode.java \
  X3DCoordinateNode.java \
  X3DNormalNode.java \
  X3DTextureCoordinateNode.java \
  X3DChildNode.java \
  X3DGeometryNode.java \
  X3DFontStyleNode.java \
  X3DComposedGeometryNode.java \
  X3DParametricGeometryNode.java \
  X3DBindableNode.java \
  X3DBackgroundNode.java \
  X3DGroupingNode.java \
  X3DShapeNode.java \
  X3DInterpolatorNode.java \
  X3DLightNode.java \
  X3DSensorNode.java \
  X3DEnvironmentalSensorNode.java \
  X3DKeyDeviceSensorNode.java \
  X3DNetworkSensorNode.java \
  X3DPointingDeviceSensorNode.java \
  X3DDragSensorNode.java \
  X3DTouchSensorNode.java \
  X3DTimeDependentNode.java \
  X3DSoundSourceNode.java \
  X3DSoundNode.java \
  X3DInfoNode.java \
  X3DSequencerNode.java \
  X3DTriggerNode.java \
  X3DScriptNode.java \
  X3DViewportNode.java \
  X3DLayerNode.java \
  X3DProductStructureChildNode.java \
  X3DViewpointNode.java \
  X3DParticleEmitterNode.java \
  X3DParticlePhysicsModelNode.java \
  X3DNBodyCollidableNode.java \
  X3DNBodyCollisionSpaceNode.java \
  X3DRigidJointNode.java \
  X3DPickingNode.java \
  X3DScriptImplementation.java \
  X3DPerFrameObserverScript.java \
  SFBool.java \
  SFColor.java \
  SFColorRGBA.java \
  SFDouble.java \
  SFFloat.java \
  SFImage.java \
  SFInt32.java \
  SFNode.java \
  SFRotation.java \
  SFString.java \
  SFTime.java \
  SFVec2d.java \
  SFVec2f.java \
  SFVec3d.java \
  SFVec3f.java \
  MField.java \
  MFBool.java \
  MFColor.java \
  MFColorRGBA.java \
  MFDouble.java \
  MFFloat.java \
  MFInt32.java \
  MFImage.java \
  MFNode.java \
  MFRotation.java \
  MFString.java \
  MFTime.java \
  MFVec2d.java \
  MFVec2f.java \
  MFVec3d.java \
  MFVec3f.java \
  Matrix3.java \
  Matrix4.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

JARS_3RDPARTY=

include ${PROJECT_ROOT}/make/Makefile.jav
