/* Generated By:JavaCC: Do not edit this line. X3DFieldParserConstants.java */
/*****************************************************************************
 *                        Web3d Consortium Copyright (c) 2001
 *                               Java Source
 *
 * This source is licensed under the GNU LGPL v2.1
 * Please read http://www.gnu.org/copyleft/lgpl.html for more information
 *
 * This software comes with the standard NO WARRANTY disclaimer for any
 * purpose. Use it at your own risk. If there's a problem you get to fix it.
 *
 *****************************************************************************/

package org.web3d.parser.x3d;

public interface X3DFieldParserConstants {

  int EOF = 0;
  int NUMBER_LITERAL = 1;
  int STRING_LITERAL = 2;
  int LBRACKET = 3;
  int RBRACKET = 4;
  int TRUE = 5;
  int FALSE = 6;
  int TRUE_L = 7;
  int FALSE_L = 8;
  int COMMENT = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<NUMBER_LITERAL>",
    "<STRING_LITERAL>",
    "\"[\"",
    "\"]\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"true\"",
    "\"false\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\",\"",
    "<COMMENT>",
  };

}
