/* Generated By:JavaCC: Do not edit this line. X3DRelaxedParserConstants.java */
/*****************************************************************************
 *                        Web3d Consortium Copyright (c) 2001
 *                               Java Source
 *
 * This source is licensed under the GNU LGPL v2.1
 * Please read http://www.gnu.org/copyleft/lgpl.html for more information
 *
 * This software comes with the standard NO WARRANTY disclaimer for any
 * purpose. Use it at your own risk. If there's a problem you get to fix it.
 *
 *****************************************************************************/
package org.web3d.parser.x3d;

public interface X3DRelaxedParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 7;
  int MULTI_LINE_COMMENT = 9;
  int NUMBER_LITERAL = 11;
  int STRING_LITERAL = 12;
  int LBRACE = 13;
  int RBRACE = 14;
  int LBRACKET = 15;
  int RBRACKET = 16;
  int DEF = 17;
  int USE = 18;
  int NULL = 19;
  int META = 20;
  int PROTO = 21;
  int INPUT_ONLY = 22;
  int OUTPUT_ONLY = 23;
  int INITIALIZE_ONLY = 24;
  int INPUT_OUTPUT = 25;
  int EXTERNPROTO = 26;
  int ROUTE = 27;
  int TO = 28;
  int IS = 29;
  int DOT = 30;
  int PROFILE = 31;
  int COMPONENT = 32;
  int EXPORT = 33;
  int IMPORT = 34;
  int AS = 35;
  int SCRIPT = 36;
  int TRUE = 37;
  int FALSE = 38;
  int ID = 39;
  int ID_FIRST = 40;
  int ID_REST = 41;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\",\"",
    "<SINGLE_LINE_COMMENT>",
    "\"#/*\"",
    "\"*/#\"",
    "<token of kind 10>",
    "<NUMBER_LITERAL>",
    "<STRING_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"DEF\"",
    "\"USE\"",
    "\"NULL\"",
    "\"META\"",
    "\"PROTO\"",
    "\"inputOnly\"",
    "\"outputOnly\"",
    "\"initializeOnly\"",
    "\"inputOutput\"",
    "\"EXTERNPROTO\"",
    "\"ROUTE\"",
    "\"TO\"",
    "\"IS\"",
    "\".\"",
    "\"PROFILE\"",
    "\"COMPONENT\"",
    "\"EXPORT\"",
    "\"IMPORT\"",
    "\"AS\"",
    "\"Script\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "<ID>",
    "<ID_FIRST>",
    "<ID_REST>",
  };

}
