#*********************************************************************
#
#  (C) 2001 - 2006 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.xj3d.ui.awt.widgets directory
#
# Author: Justin Couch
# Version: $Revision: 1.7 $
#
#*********************************************************************

PACKAGE = org.xj3d.ui.awt.widgets

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  IconLoader.java \
  SelectableFileFilter.java \
  VRMLFileFilter.java \
  Web3DFileFilter.java \
  X3DFileFilter.java \
  DynamicGridLayout.java \
  OpenAction.java \
  NextViewpointAction.java \
  PreviousViewpointAction.java \
  HomeViewpointAction.java \
  LookatAction.java \
  FitWorldAction.java \
  NavModeAction.java \
  LoadURLAction.java \
  ReloadAction.java \
  SwingProgressListener.java \
  SwingTextAreaOutputStream.java \
  SwingConsoleWindow.java \
  SwingNavigationToolbar.java \
  ViewpointCellRenderer.java \
  SwingViewpointToolbar.java \
  SwingLocationToolbar.java \
  SwingConsoleButton.java \
  SwingStatusBar.java \
  AWTProgressListener.java \
  AWTConsoleWindow.java \
  CursorManager.java \

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = j3d-org-all_0.9.0.jar uri.jar

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =


include ${PROJECT_ROOT}/make/Makefile.jav
