#*********************************************************************
#
#  (C) 2004 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the xj3d.browser directory
#
# Author: Alan Hudson
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = xj3d.browser.renderer

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = BrowserComponent.java \
         BrowserComponentFactory.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY=

include ${PROJECT_ROOT}/make/Makefile.jav
