#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.web3d.vrml.renderer.common.nodes.texture
# directory
#
# Author: Justin Couch
# Version: $Revision: 1.12 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.renderer.common.nodes.texture

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = BaseTextureCoordinate.java \
	BaseTextureTransform.java \
	BaseMultiTexture.java \
	BaseMultiTextureTransform.java \
	BaseMultiTextureCoordinate.java \
	BaseTextureCoordinateGenerator.java \
	BaseMovieTexture.java \
	BasePixelTexture.java \
	BaseImageTexture.java \
	BaseTextureCoordinate3D.java \
	BaseTextureCoordinate4D.java \
	BaseTextureTransform3D.java \
	BaseComposedTexture3D.java \
	BasePixelTexture3D.java \
	BaseImageTexture3D.java \
	BaseComposedCubeMapTexture.java \
	BasePixelCubeMapTexture.java \
	BaseImageCubeMapTexture.java \
	BaseRenderedTexture.java \
	BaseTextureProperties.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY =

include ${PROJECT_ROOT}/make/Makefile.jav
