
PACKAGE = org.web3d.x3d.sai.rigidbodyphysics

SOURCE = \
  BallJoint.java \
  CollidableOffset.java \
  CollidableShape.java \
  CollisionCollection.java \
  CollisionSensor.java \
  CollisionSpace.java \
  Contact.java \
  DoubleAxisHingeJoint.java \
  MotorJoint.java \
  RigidBodyCollection.java \
  SingleAxisHingeJoint.java \
  SliderJoint.java \
  UniversalJoint.java \

include ${PROJECT_ROOT}/make/Makefile.jav
