#*********************************************************************
#
#  (C) 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Justin Couch
# Version: $Revision: 1.3 $
#
#*********************************************************************

PACKAGE = 3.2/component

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = \
  xj3d_Clipping.xml \
  xj3d_DIS.xml \
  xj3d_EnvironmentTexturing.xml \
  xj3d_Fog.xml \
  xj3d_IODevice.xml \
  xj3d_Overlay.xml \
  xj3d_PickingUtilities.xml \
  xj3d_RenderedTexture.xml \
  xj3d_RigidBodyPhysics.xml \
  xj3d_Shape.xml \
  xj3d_Sound.xml \
  xj3d_Texture.xml

include $(PROJECT_ROOT)/make/Makefile.config
