
PACKAGE = org.web3d.x3d.sai.environmentaleffects

SOURCE = \
  Background.java \
  Fog.java \
  FogCoordinate.java \
  LocalFog.java \
  TextureBackground.java \

include ${PROJECT_ROOT}/make/Makefile.jav
