#*********************************************************************
#
#  (C) 2001 - 2006 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.xj3d.ui.awt.browser.j3d directory
#
# Author: Justin Couch
# Version: $Revision: 1.3 $
#
#*********************************************************************

PACKAGE = org.xj3d.ui.awt.browser.j3d

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  X3DBrowserJPanel.java \
  VRMLBrowserJPanel.java \
  X3DBrowserAWTPanel.java \
  VRMLBrowserAWTPanel.java \
  J3DBrowserFactoryImpl.java \
  X3DJ3DBrowserFactoryImpl.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

JARS_3RDPARTY=uri.jar j3d-org-all_0.9.0.jar

include ${PROJECT_ROOT}/make/Makefile.jav
