#*********************************************************************
#
#  (C) 2001 - 2006 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile for the org.web3d.vrml.nodes directory
#
# Author: Justin Couch
# Version: $Revision: 1.98 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.nodes

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = FrameStateListener.java \
  FrameStateManager.java \
  NavigationInfoChangeListener.java \
  MaterialColorListener.java \
  MaterialColorListenerMulticaster.java \
  VRMLFieldData.java \
  VRMLFieldDataThreaded.java \
  VRMLTimeListener.java \
  VRMLClock.java \
  VRMLNodeListener.java \
  ViewpointListener.java \
  LayerListener.java \
  NodeListenerMulticaster.java \
  VRMLMetadataObjectNodeType.java \
  VRMLNodeType.java \
  VRMLWorldRootChildNodeType.java \
  VRMLNodeComponentListener.java \
  VRMLUrlListener.java \
  VRMLContentStateListener.java \
  VRMLViewDependentNodeType.java \
  VRMLExternalSynchronizedNodeType.java \
  VRMLExternalNodeType.java \
  VRMLSingleExternalNodeType.java \
  VRMLMultiExternalNodeType.java \
  VRMLChildNodeType.java \
  VRMLBindableNodeListener.java \
  VRMLBindableNodeType.java \
  VRMLBoundedNodeType.java \
  VRMLGroupingNodeType.java \
  VRMLWorldRootNodeType.java \
  VRMLTimeDependentNodeType.java \
  VRMLTimeControlledNodeType.java \
  VRMLAudioClipNodeType.java \
  VRMLViewpointNodeType.java \
  VRMLAppearanceChildNodeType.java \
  VRMLSurfaceMaterialNodeType.java \
  VRMLVisualMaterialNodeType.java \
  VRMLMaterialNodeType.java \
  VRMLTextureListener.java \
  VRMLTextureNodeType.java \
  VRMLTexture2DNodeType.java \
  VRMLTexture3DNodeType.java \
  VRMLComposedTextureNodeType.java \
  VRMLTextureProperties2DNodeType.java \
  VRMLMultiTextureNodeType.java \
  VRMLEnvironmentTextureNodeType.java \
  VRMLTextureTransformNodeType.java \
  VRMLTextureCoordinateTransformNodeType.java \
  VRMLAppearanceNodeType.java \
  VRMLGeometricPropertyNodeType.java \
  VRMLVisualMaterialNodeType.java \
  VRMLColorNodeType.java \
  VRMLCoordinateNodeType.java \
  VRMLSensorNodeType.java \
  VRMLKeyDeviceSensorNodeType.java \
  VRMLPickingSensorNodeType.java \
  VRMLPickableNodeType.java \
  VRMLPointingDeviceSensorNodeType.java \
  VRMLDragSensorNodeType.java \
  VRMLEnvironmentalSensorNodeType.java \
  VRMLFontStyleNodeType.java \
  LocalColorsListener.java \
  TexCoordGenModeListener.java \
  VRMLGeometryNodeType.java \
  VRMLShapeNodeType.java \
  VRMLInterpolatorNodeType.java \
  VRMLLightNodeType.java \
  VRMLInlineNodeType.java  \
  VRMLScriptNodeType.java \
  VRMLNormalNodeType.java \
  VRMLSoundNodeType.java \
  VRMLParametricGeometryNodeType.java \
  VRMLTextureCoordinateNodeType.java \
  VRMLTouchSensorNodeType.java \
  VRMLBackgroundNodeType.java \
  VRMLFogNodeType.java \
  VRMLNavigationInfoNodeType.java \
  VRMLLinkNodeType.java \
  VRMLProtoDeclare.java \
  VRMLExternProtoDeclare.java \
  VRMLComponentGeometryNodeType.java \
  VRMLTextNodeType.java \
  VRMLSurfaceLayoutListener.java \
  VRMLSurfaceChildNodeType.java \
  VRMLSurfaceLayoutNodeType.java \
  VRMLSurfaceNodeType.java \
  VRMLOverlayNodeType.java \
  VRMLCollidableNodeType.java \
  VRMLParticleEmitterNodeType.java \
  VRMLParticlePhysicsModelNodeType.java \
  VRMLParticleSystemNodeType.java \
  VRMLSequencerNodeType.java \
  VRMLHAnimNodeType.java \
  VRMLHAnimHumanoidNodeType.java \
  VRMLSoundStateListener.java \
  VRMLNBodyCollidableNodeType.java \
  VRMLNBodySpaceNodeType.java \
  VRMLNBodyGroupNodeType.java \
  VRMLNBodySensorNodeType.java \
  VRMLRigidJointNodeType.java \
  VRMLRigidBodyNodeType.java \
  VRMLRigidBodyGroupNodeType.java \
  VRMLPointPropertiesNodeType.java \
  VRMLAnnotationNodeType.java \
  VRMLViewportNodeType.java \
  VRMLLayerNodeType.java \
  VRMLLayerSetNodeType.java \
  VRMLScene.java \
  VRMLProtoInstance.java \
  SceneGraphTraversalSimpleObserver.java \
  SceneGraphTraversalDetailObserver.java \
  SceneGraphTraverser.java  \
  VRMLTerrainSource.java \
  NetworkRoleListener.java \
  VRMLNetworkInterfaceNodeType.java \
  VRMLDISNodeType.java \
  VRMLDISManagerNodeType.java \
  VRMLProductStructureChildNodeType.java \
  VRMLDeviceSensorNodeType.java \
  VRMLDeviceManagerNodeType.java \
  VRMLLocalOriginNodeType.java \
  ImportNodeProxy.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = vecmath.jar dis.jar disxml.jar j3d-org-all_0.9.0.jar odejava.jar

include ${PROJECT_ROOT}/make/Makefile.jav
