#*********************************************************************
#
#  (C) 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = 3.0

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = profiles.xml \
	xj3d-devices.properties \
	xj3d-devices-j3d.properties \
	xj3d-devices-ogl.properties \
	XMLcontainerfields.properties \


include $(PROJECT_ROOT)/make/Makefile.config
