#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.web3d.vrml.scripting.ecmascript.builtin
# directory
#
# Author: Justin Couch
# Version: $Revision: 1.13 $
#
#*********************************************************************

PACKAGE = org.web3d.vrml.scripting.ecmascript.builtin

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
    FieldFactory.java \
    FieldExtras.java \
    FieldScriptableObject.java \
    AbstractScriptableObject.java \
    NodeImplSource.java \
    ReusableFloat.java \
    ReusableInteger.java \
    ReusableDouble.java \
    NodeFieldData.java \
    NodeFieldObject.java \
    X3DFieldDefinition.java \
    FieldDefinitionArray.java \
    SFColor.java \
    SFColorRGBA.java \
    SFVec2f.java \
    SFVec3f.java \
    SFVec4f.java \
    SFVec2d.java \
    SFVec3d.java \
    SFVec4d.java \
    SFRotation.java \
    SFNode.java \
    MFColor.java \
    MFColorRGBA.java \
    MFInt32.java \
    MFBool.java \
    MFFloat.java \
    MFDouble.java \
    MFTime.java \
    MFString.java \
    MFNode.java \
    MFRotation.java \
    MFVec2f.java \
    MFVec3f.java \
    MFVec4f.java \
    MFVec2d.java \
    MFVec3d.java \
    MFVec4d.java \
    SFImage.java \
    MFImage.java \
    ECMAFieldFactory.java \
    Matrix3.java \
    Matrix4.java \
    VrmlMatrix.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = vecmath.jar js.jar


include ${PROJECT_ROOT}/make/Makefile.jav
