#*********************************************************************
#
#  (C) 2005 - 2006 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Alan Hudson
# Version: $Revision: 1.2 $
#
#*********************************************************************

PACKAGE = locationbar

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = openIcon32x32.gif \
        reloadIcon32x32.gif \
	goIcon32x32.gif

include $(PROJECT_ROOT)/make/Makefile.images
