#*********************************************************************
#
#  (C) 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Alan Hudson
# Version: $Revision: 1.2 $
#
#*********************************************************************

# Names of packages to be compiled. These are declared in the order that
# they are to be compiled in. We create one at a time
BUILD_ORDER = DTD

# 3rd party libraries that need including.
JARS_3RDPARTY=

# Names of JAR files we want to create
JARS = xj3d-xml.jar

include $(PROJECT_ROOT)/make/Makefile.xmlextras
