#*********************************************************************
#
#  (C) 2005 Web3d Consortium
#    http://www.web3d.org/
#
# Author: Alan Hudson
# Version: $Revision: 1.2 $
#
#*********************************************************************

PACKAGE = DTD

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = DistributedInteractiveSimulation.dtd \
    GeoSpatial.dtd \
    HumanoidAnimation.dtd \
    LatticeXvl.dtd \
    Nurbs.dtd \
    Xj3D_overlay.dtd \
    x3d-3.0-InputOutputFields.dtd \
    x3d-3.0-Web3dExtensions.dtd \
    x3d-3.0-Web3dExtensionsPrivate.dtd \
    x3d-3.0-Web3dExtensionsPublic.dtd \
    x3d-3.0.dtd \
    x3d-3.1-InputOutputFields.dtd \
    x3d-3.1-Web3dExtensionsPrivate.dtd \
    x3d-3.1-Web3dExtensionsPublic.dtd \
    x3d-3.1.dtd \


include $(PROJECT_ROOT)/make/Makefile.xmlextras
