#*********************************************************************
#
#  (C) 2001 - 2006 Web3D Consortium
#    http://www.web3d.org/
#
# Package makefile producing xnorender-norender.jar
#
# Author: Justin Couch
# Version: $Revision: 1.18 $
#
#*********************************************************************

# A version number we tack onto the JAR file name for eclipse versioning
# purposes.
JAR_VERSION=2.0.0

# Describe every directory that you want included in the JAR file here.
# This is not recursive, so if you want parent directory and the
# sub-directory, say so. These directories should not have '/' appended.
JAR_CONTENT=org/web3d/vrml/renderer/norender \
	org/web3d/vrml/renderer/norender/browser \
	org/web3d/vrml/renderer/norender/nodes \
	org/web3d/vrml/renderer/norender/nodes/cadgeometry \
	org/web3d/vrml/renderer/norender/nodes/core \
	org/web3d/vrml/renderer/norender/nodes/dis \
	org/web3d/vrml/renderer/norender/nodes/environment \
	org/web3d/vrml/renderer/norender/nodes/enveffects \
	org/web3d/vrml/renderer/norender/nodes/eventutils \
	org/web3d/vrml/renderer/norender/nodes/extensions \
	org/web3d/vrml/renderer/norender/nodes/geom2d \
	org/web3d/vrml/renderer/norender/nodes/geom3d \
	org/web3d/vrml/renderer/norender/nodes/geospatial \
	org/web3d/vrml/renderer/norender/nodes/group \
	org/web3d/vrml/renderer/norender/nodes/hanim \
	org/web3d/vrml/renderer/norender/nodes/interpolator \
	org/web3d/vrml/renderer/norender/nodes/layering \
	org/web3d/vrml/renderer/norender/nodes/lighting \
	org/web3d/vrml/renderer/norender/nodes/navigation \
	org/web3d/vrml/renderer/norender/nodes/networking \
	org/web3d/vrml/renderer/norender/nodes/nurbs \
	org/web3d/vrml/renderer/norender/nodes/particle \
	org/web3d/vrml/renderer/norender/nodes/picking \
	org/web3d/vrml/renderer/norender/nodes/render \
	org/web3d/vrml/renderer/norender/nodes/rigidphysics \
	org/web3d/vrml/renderer/norender/nodes/scripting \
	org/web3d/vrml/renderer/norender/nodes/sensor \
	org/web3d/vrml/renderer/norender/nodes/shape \
	org/web3d/vrml/renderer/norender/nodes/sound \
	org/web3d/vrml/renderer/norender/nodes/surface \
	org/web3d/vrml/renderer/norender/nodes/text \
	org/web3d/vrml/renderer/norender/nodes/texture \
	org/web3d/vrml/renderer/norender/nodes/time \

# Manifest file name. Stored in the make/manifest directory
MANIFEST=xj3d-norender.mf

include ${PROJECT_ROOT}/make/Makefile.jav
