#*********************************************************************
#
#  (C) 2001 - 2006 Web3d Consortium
#    http://www.web3d.org/
#
# Package makefile producing xj3d-common.jar
#
# Author: Justin Couch
# Version: $Revision: 1.22 $
#
#*********************************************************************

# A version number we tack onto the JAR file name for eclipse versioning
# purposes.
JAR_VERSION=2.0.0

# Describe every directory that you want included in the JAR file here.
# This is not recursive, so if you want parent directory and the
# sub-directory, say so. These directories should not have '/' appended.
JAR_CONTENT=org/web3d/vrml/renderer/common/browser \
	org/web3d/vrml/renderer/common/input \
	org/web3d/vrml/renderer/common/input/dis \
	org/web3d/vrml/renderer/common/input/movie \
	org/web3d/vrml/renderer/common/geospatial \
	org/web3d/vrml/renderer/common/nodes \
	org/web3d/vrml/renderer/common/nodes/cadgeometry \
	org/web3d/vrml/renderer/common/nodes/core \
	org/web3d/vrml/renderer/common/nodes/dis \
	org/web3d/vrml/renderer/common/nodes/enveffects \
	org/web3d/vrml/renderer/common/nodes/environment \
	org/web3d/vrml/renderer/common/nodes/eventutils \
	org/web3d/vrml/renderer/common/nodes/extensions \
	org/web3d/vrml/renderer/common/nodes/geom2d \
	org/web3d/vrml/renderer/common/nodes/geom3d \
	org/web3d/vrml/renderer/common/nodes/geospatial \
	org/web3d/vrml/renderer/common/nodes/group \
	org/web3d/vrml/renderer/common/nodes/hanim \
	org/web3d/vrml/renderer/common/nodes/interpolator \
	org/web3d/vrml/renderer/common/nodes/layering \
	org/web3d/vrml/renderer/common/nodes/lighting \
	org/web3d/vrml/renderer/common/nodes/navigation \
	org/web3d/vrml/renderer/common/nodes/networking \
	org/web3d/vrml/renderer/common/nodes/nurbs \
	org/web3d/vrml/renderer/common/nodes/particle \
	org/web3d/vrml/renderer/common/nodes/picking \
	org/web3d/vrml/renderer/common/nodes/render \
	org/web3d/vrml/renderer/common/nodes/rigidphysics \
	org/web3d/vrml/renderer/common/nodes/scripting \
	org/web3d/vrml/renderer/common/nodes/sensor \
	org/web3d/vrml/renderer/common/nodes/shape \
	org/web3d/vrml/renderer/common/nodes/sound \
	org/web3d/vrml/renderer/common/nodes/surface \
	org/web3d/vrml/renderer/common/nodes/text \
	org/web3d/vrml/renderer/common/nodes/texture \
	org/web3d/vrml/renderer/common/nodes/time \



# Manifest file name. Stored in the make/manifest directory
MANIFEST=xj3d-common.mf

include ${PROJECT_ROOT}/make/Makefile.jav
