#*********************************************************************
#
#  (C) 2006 Web3d Consortium
#    http://www.web3d.org/
# 
# Package makefile for the org.web3d.image directory
#
# Author: Rex Melton
# Version: $Revision: 1.3 $
#
#*********************************************************************

PACKAGE = org.web3d.image

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  NIOBufferImageType.java \
  NIOBufferImage.java \
  ScaleFilter.java \
  AreaAveragingScaleFilter.java \
  BilinearScaleFilter.java \


# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

JARS_3RDPARTY=

include ${PROJECT_ROOT}/make/Makefile.jav
