
PACKAGE = org.web3d.x3d.sai.layering

SOURCE = \
  CustomViewport.java \
  FixedViewport.java \
  Layer.java \
  LayerSet.java \
  ProportionalViewport.java \

include ${PROJECT_ROOT}/make/Makefile.jav
