#*********************************************************************
#
#  (C) 2003 - 2006 Yumetech, Inc
#    http://www.j3d.org/
#
# Package makefile for the org.j3d.aviatrix3d.rendering directory
#
# Author: Justin Couch
# Version: $Revision: 2.8 $
#
#*********************************************************************

PACKAGE = org.j3d.aviatrix3d.rendering

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  BoundingVolume.java \
  Renderable.java \
  BufferStateRenderable.java \
  Cullable.java \
  LeafCullable.java \
  EnvironmentCullable.java \
  ProfilingData.java \
  RenderEffectsProcessor.java \
  ViewEnvironmentCullable.java \
  RenderPassCullable.java \
  SceneCullable.java \
  ViewportLayerCullable.java \
  ViewportCullable.java \
  LayerCullable.java \
  OffscreenCullable.java \
  DeletableRenderable.java \
  ComponentRenderable.java \
  AudioRenderable.java \
  ObjectRenderable.java \
  BackgroundRenderable.java \
  EffectRenderable.java \
  ShaderComponentRenderable.java \
  ShaderRenderable.java \
  ShaderSourceRenderable.java \
  AppearanceAttributeRenderable.java \
  TextureRenderable.java \
  AppearanceRenderable.java \
  GeometryRenderable.java \
  CustomGeometryRenderable.java \
  ShapeRenderable.java \
  RenderableInstructions.java \
  CustomRenderable.java \
  SingleCullable.java \
  GroupCullable.java \
  TransformCullable.java \
  CullInstructions.java \
  CustomCullable.java \

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA =

# If the package requires extra classes outside the JDK, the JAR files that
# are required are listed here. These should be found in ${PROJECT_ROOT}/lib
JARS_3RDPARTY = 

include ${PROJECT_ROOT}/make/Makefile.jav
