
PACKAGE = org.xj3d.sai.internal.node.geospatial

SOURCE = \
  SAIGeoCoordinate.java \
  SAIGeoElevationGrid.java \
  SAIGeoLocation.java \
  SAIGeoLOD.java \
  SAIGeoMetadata.java \
  SAIGeoOrigin.java \
  SAIGeoPositionInterpolator.java \
  SAIGeoTouchSensor.java \
  SAIGeoTransform.java \
  SAIGeoViewpoint.java \

include ${PROJECT_ROOT}/make/Makefile.jav
