
PACKAGE = org.web3d.x3d.sai.geospatial

SOURCE = \
  GeoCoordinate.java \
  GeoElevationGrid.java \
  GeoLocation.java \
  GeoLOD.java \
  GeoMetadata.java \
  GeoOrigin.java \
  GeoPositionInterpolator.java \
  GeoTouchSensor.java \
  GeoTransform.java \
  GeoViewpoint.java \

include ${PROJECT_ROOT}/make/Makefile.jav
