#*********************************************************************
#
#  (C) 2001 Web3d Consortium
#    http://www.web3d.org/
# 
# Author: Justin Couch
# Version: $Revision: 1.4 $
#
#*********************************************************************

GRAMMAR=x3d

OUTPUT_PACKAGE=org.web3d.parser.x3d

# Names of grammars to be compiled. These are declared in the order that
# they are to be generated in. We create one at a time
SOURCE = X3DField.jj \
	X3DRelaxed.jj


include $(PROJECT_ROOT)/make/Makefile.javacc
